INFO     [🔧TEST CONFIG]:conftest.py:82 Loading test configuration
INFO     [🔧TEST CONFIG]:conftest.py:273 Starting browser in a headless mode...
INFO     [🔧TEST CONFIG]:conftest.py:286 Initializing new browser context
INFO     [🔧TEST CONFIG]:conftest.py:294 Navigating to: https://console.dev.apolo.us/
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body:
<not available>
Response Body (first 1000 chars):
{"authorized": false, "auth_url": "https://auth.dev.apolo.us/authorize", "token_url": "https://auth.dev.apolo.us/oauth/token", "logout_url": "https://auth.dev.apolo.us/v2/logout?returnTo=https://console.dev.apolo.us", "client_id": "q3I0OzzGnTDkhRmpeJ7WWgaTCucmVxTL", "audience": "https://api.dev.apolo.us", "callback_urls": ["http://127.0.0.1:54540", "http://127.0.0.1:54541", "http://127.0.0.1:54542"], "headless_callback_url": "https://api.dev.apolo.us/oauth/show-code", "success_redirect_url": "https://api.dev.apolo.us/oauth/login"}
INFO     [🔧TEST CONFIG]:conftest.py:88 Creating data manager
INFO     [🔧TEST CONFIG]:conftest.py:114 Creating users manager
INFO     [🔧TEST CONFIG]:conftest.py:100 Creating API helper
INFO     [🔧TEST CONFIG]:conftest.py:108 Creating Apolo CLI instance
INFO     [🔧TEST CONFIG]:conftest.py:136 Continue using UserData(email='regression-nia1431su0@apolo.us', username='regression-nia1431su0', password='I^NnejkHnX3%') as main test user...
INFO     [👤UsersManager]:users_manager.py:73 Setting main user to UserData(email='regression-nia1431su0@apolo.us', username='regression-nia1431su0', password='I^NnejkHnX3%')
INFO     [🔧TEST CONFIG]:conftest.py:169 Continue using UserData(email='regression-zljxjq6gs5@apolo.us', username='regression-zljxjq6gs5', password='P*EwwXpuxbF$') as second test user...
INFO     [👤UsersManager]:users_manager.py:82 Setting second user to UserData(email='regression-zljxjq6gs5@apolo.us', username='regression-zljxjq6gs5', password='P*EwwXpuxbF$')
INFO     [🔧TEST CONFIG]:conftest.py:173 Continue using UserData(email='regression-640twlj1gn@apolo.us', username='regression-640twlj1gn', password='p#OPaMn$k7QO') as third test user...
INFO     [👤UsersManager]:users_manager.py:91 Setting third user to UserData(email='regression-640twlj1gn@apolo.us', username='regression-640twlj1gn', password='p#OPaMn$k7QO')
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Apolo CLI client is installed
INFO     [🖥apolo_CLI]:apolo_runner.py:25 check CLI version. Running command via cli:

apolo --version

INFO     [🖥apolo_CLI]:apolo_runner.py:86 check CLI version succeeded:

Apolo Platform Client 25.7.2

INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Apolo CLI client is installed
INFO     [📘TEST_INFO]:reporting.py:86 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:87 📝 TEST started: User verifies config show output via CLI
INFO     [📘TEST_INFO]:reporting.py:88 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Login via UI
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click login button
INFO     [🎭 Playwright]:base_page.py:16 <AuthPage>: Click log in button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click login button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_login_button_success_2250f8.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter email
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter regression-nia1431su0@apolo.us email
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter email
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_email_success_47d286.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter password
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter ********* password
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter password
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_password_success_6e522e.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Continue button
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Click continue button
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Waiting for spinner
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body:
<not available>
Response Body (first 1000 chars):
{"authorized": true, "orgs": [], "clusters": [], "projects": [], "admin_url": "https://api.dev.apolo.us/apis/admin/v1", "auth_url": "https://auth.dev.apolo.us/authorize", "token_url": "https://auth.dev.apolo.us/oauth/token", "logout_url": "https://auth.dev.apolo.us/v2/logout?returnTo=https://console.dev.apolo.us", "client_id": "q3I0OzzGnTDkhRmpeJ7WWgaTCucmVxTL", "audience": "https://api.dev.apolo.us", "callback_urls": ["http://127.0.0.1:54540", "http://127.0.0.1:54541", "http://127.0.0.1:54542"], "headless_callback_url": "https://api.dev.apolo.us/oauth/show-code", "success_redirect_url": "https://api.dev.apolo.us/oauth/login"}
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/api/v1/users/regression-nia1431su0/permissions?uri=blob:
Request Body:
<not available>
Response Body (first 1000 chars):
[]
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Waiting for spinner to disappear
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/invites/incoming
Request Body:
<not available>
Response Body (first 1000 chars):
[]
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-nia1431su0?include=clusters&include=system_role
Request Body:
<not available>
Response Body (first 1000 chars):
{"name": "regression-nia1431su0", "email": "regression-nia1431su0@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-08-21T01:33:10.378997+00:00", "terms_accepted": true, "clusters": []}
WARNING  [🔧TEST CONFIG]:conftest.py:342 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-nia1431su0?include=orgs
Request Body:
<not available>
Response Body (first 1000 chars):
{"name": "regression-nia1431su0", "email": "regression-nia1431su0@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-08-21T01:33:10.378997+00:00", "terms_accepted": true, "orgs": []}
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Continue button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_continue_button_success_428237.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Welcome new user page displayed
INFO     [🎭 Playwright]:base_page.py:16 <WelcomeNewUserPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Welcome new user page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_0c8140.png
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Login via UI
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_login_success_17757e.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Login to apolo CLI with access token
INFO     [🖥apolo_CLI]:apolo_runner.py:25 login-with-token. Running command via cli:

apolo config login-with-token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjhyNXZCR0E4ZXNuc1IzbXJ0NUFSViJ9.eyJodHRwczovL3BsYXRmb3JtLm5ldXJvbWF0aW9uLmlvL3VzZXIiOiJyZWdyZXNzaW9uLW5pYTE0MzFzdTAiLCJodHRwczovL3BsYXRmb3JtLm5ldXJvbWF0aW9uLmlvL2xvZ2luX3JlZGlyZWN0X3VybCI6Imh0dHBzOi8vY29uc29sZS5kZXYuYXBvbG8udXMiLCJodHRwczovL3BsYXRmb3JtLmFwb2xvLnVzL29yaWdpbiI6Imh0dHBzOi8vY29uc29sZS5kZXYuYXBvbG8udXMiLCJpc3MiOiJodHRwczovL2F1dGguZGV2LmFwb2xvLnVzLyIsInN1YiI6ImF1dGgwfDY4YTY3NzRhMzU0NTY1MTJmNGJlZGE1ZCIsImF1ZCI6WyJodHRwczovL2FwaS5kZXYuYXBvbG8udXMiLCJodHRwczovL2Rldi1hcG9sby11cy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU1NzQyOTM1LCJleHAiOjE3NTU4MjkzMzUsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiJxM0kwT3p6R25URGtoUm1wZUo3V1dnYVRDdWNtVnhUTCJ9.tDf1hxHwuCbGAGK6uVcu4gaZ7ukKhU8bl-x2Tt_sPi8uy5BjalH8pASX25xJXRF0AEHkZKYjMvgYAbi149YjFhMbH-5TCvaYv1y1oZhCFGZ2VUCgJG5IuISvESX6mU94kLvfAS0ZvnOx_KgPe0GvgWmnfdSS_gM-xxPCw8ptIFP4mEwxyHJ0tTjpBnRktBuxOYMlcWOAgrCmCwBBIXeE3yP-ED0t-donMu7rB_r9VERqayckWva-PxNbGw1K1SJIM9KuFil2k5i4Qnj1max6E8fCEd0NPqhPs_JwlKh4U70NECIQtcML8xDgzvyJwtE9iAfEsjUe4dzzThNVIJtlpg https://api.dev.apolo.us/api/v1

INFO     [🖥apolo_CLI]:apolo_runner.py:86 login-with-token succeeded:

Logged into https://api.dev.apolo.us/api/v1 as regression-nia1431su0
Read the docs at https://docs.apolo.us or run `apolo --help` to see the reference

INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Login to apolo CLI with access token
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Add new organization via apolo CLI
INFO     [🔧DATA MANAGER]:test_data.py:48 Added organization: org_name=regression-org-sqq4g5zwfk24, gherkin_name=My-organization
INFO     [🖥apolo_CLI]:apolo_runner.py:25 create organization 'regression-org-sqq4g5zwfk24'. Running command via cli:

apolo admin add-org regression-org-sqq4g5zwfk24

INFO     [🖥apolo_CLI]:apolo_runner.py:86 create organization 'regression-org-sqq4g5zwfk24' succeeded:



INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Add new organization via apolo CLI
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Run config show command via CLI
INFO     [🖥apolo_CLI]:apolo_runner.py:25 show config info. Running command via cli:

apolo config show

ERROR    [🖥apolo_CLI]:apolo_runner.py:82 show config info failed:

Your root certificates are out of date.
You are using certifi 2025.7.14, however 2025.8.3 is available.
Please consider upgrading certifi package, e.g.:
    python -m pip install --upgrade certifi
or
    conda update certifi

ERROR: Not enough permissions ({"missing": [{"uri": "cluster://default/users/regression-5fuceonhct", "action": "read"}]})


ERROR    [📘TEST_INFO]:reporting.py:56 ❌ STEP failed: Run config show command via CLI
ERROR    [📘TEST_INFO]:reporting.py:95 ❌ TEST failed: User verifies config show output via CLI
Exception: [AssertionError] during step: Run config show command via CLI
Message: Your root certificates are out of date.
You are using certifi 2025.7.14, however 2025.8.3 is available.
Please consider upgrading certifi package, e.g.:
    python -m pip install --upgrade certifi
or
    conda update certifi

ERROR: Not enough permissions ({"missing": [{"uri": "cluster://default/users/regression-5fuceonhct", "action": "read"}]})
INFO     [📘TEST_INFO]:reporting.py:98 ------------------------------------------------------------
INFO     [🌐API_helper]:api_helper.py:44 GET https://api.dev.apolo.us/apis/admin/v1/orgs
INFO     [🌐API_helper]:api_helper.py:135 Status: 200. Response: []
INFO     [🔧TEST CONFIG]:conftest.py:218 Cleaning up 0 organisations
INFO     [🔧TEST CONFIG]:conftest.py:248 Closing all browser sessions
INFO     [🔧TEST CONFIG]:conftest.py:252 Closed context
INFO     [🔧TEST CONFIG]:conftest.py:259 Closed browser
INFO     [🔧TEST CONFIG]:conftest.py:264 Closed all browser sessions