{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"AssertionError: [AssertionError] during step: Update user role on a project via CLI\nMessage:  Expected: ERROR: Illegal argument(s) (Last project admin cannot be demoted), got: Your root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: Illegal argument(s) (Last project admin cannot be demoted)","children":[{"name":"Admin demote himself to Manager in project via CLI","uid":"eb717567d5b1c581","parentUid":"e99fd585af277dcd69ee7eab786d2445","status":"failed","time":{"start":1756801369346,"stop":1756801391012,"duration":21666},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"e99fd585af277dcd69ee7eab786d2445"},{"name":"AssertionError: [AssertionError] during step: Remove user from project via CLI\nMessage:  Expected: ERROR: Illegal argument(s) (Last project admin cannot be removed), got: Your root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: Illegal argument(s) (Last project admin cannot be removed)","children":[{"name":"Admin removes himself from project via CLI","uid":"4d13a27cfa016ce9","parentUid":"479dc39cce91958685ded324dcf8bb44","status":"failed","time":{"start":1756802782509,"stop":1756802840212,"duration":57703},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"479dc39cce91958685ded324dcf8bb44"},{"name":"AssertionError: [AssertionError] during step: Add user not in organization to project via CLI\nMessage: Expected: \nERROR: User 'regression-org-9zhnw22hxp7s/regression-8gt7hgucb1' not found in cluster 'default' \nbut got \nYour root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: User 'regression-org-9zhnw22hxp7s/regression-8gt7hgucb1' not found in cluster 'default'","children":[{"name":"Add user not in organization to project via CLI","uid":"987d0f7a43a346a0","parentUid":"6c02c4e1e5a33428a5c956ac3dfa64bb","status":"failed","time":{"start":1756805323346,"stop":1756805365410,"duration":42064},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"6c02c4e1e5a33428a5c956ac3dfa64bb"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}